/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as UUsernameIndexRouteImport } from './routes/u.$username.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as UUsernameAboutRouteImport } from './routes/u.$username.about'
import { Route as AuthenticatedAdminSiteSettingsRouteImport } from './routes/_authenticated/admin.site-settings'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminRecognitionRouteImport } from './routes/_authenticated/admin.recognition'
import { Route as AuthenticatedAdminProfileRouteImport } from './routes/_authenticated/admin.profile'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminHeroRouteImport } from './routes/_authenticated/admin.hero'
import { Route as AuthenticatedAdminCredentialsRouteImport } from './routes/_authenticated/admin.credentials'
import { Route as AuthenticatedAdminCaseStudiesRouteImport } from './routes/_authenticated/admin.case-studies'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as UUsernameProjectsIndexRouteImport } from './routes/u.$username.projects.index'
import { Route as UUsernameCaseStudiesIndexRouteImport } from './routes/u.$username.case-studies.index'
import { Route as UUsernameBlogIndexRouteImport } from './routes/u.$username.blog.index'
import { Route as AuthenticatedAdminProjectsIndexRouteImport } from './routes/_authenticated/admin.projects.index'
import { Route as AuthenticatedAdminBlogIndexRouteImport } from './routes/_authenticated/admin.blog.index'
import { Route as UUsernameProjectsSlugRouteImport } from './routes/u.$username.projects.$slug'
import { Route as UUsernameCaseStudiesSlugRouteImport } from './routes/u.$username.case-studies.$slug'
import { Route as UUsernameBlogSlugRouteImport } from './routes/u.$username.blog.$slug'
import { Route as AuthenticatedAdminProjectsIdRouteImport } from './routes/_authenticated/admin.projects.$id'
import { Route as AuthenticatedAdminBlogIdRouteImport } from './routes/_authenticated/admin.blog.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const UUsernameIndexRoute = UUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UUsernameRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const UUsernameAboutRoute = UUsernameAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => UUsernameRoute,
} as any)
const AuthenticatedAdminSiteSettingsRoute =
  AuthenticatedAdminSiteSettingsRouteImport.update({
    id: '/site-settings',
    path: '/site-settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRecognitionRoute =
  AuthenticatedAdminRecognitionRouteImport.update({
    id: '/recognition',
    path: '/recognition',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProfileRoute =
  AuthenticatedAdminProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHeroRoute = AuthenticatedAdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCredentialsRoute =
  AuthenticatedAdminCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCaseStudiesRoute =
  AuthenticatedAdminCaseStudiesRouteImport.update({
    id: '/case-studies',
    path: '/case-studies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameProjectsIndexRoute = UUsernameProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => UUsernameRoute,
} as any)
const UUsernameCaseStudiesIndexRoute =
  UUsernameCaseStudiesIndexRouteImport.update({
    id: '/case-studies/',
    path: '/case-studies/',
    getParentRoute: () => UUsernameRoute,
  } as any)
const UUsernameBlogIndexRoute = UUsernameBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => UUsernameRoute,
} as any)
const AuthenticatedAdminProjectsIndexRoute =
  AuthenticatedAdminProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogIndexRoute =
  AuthenticatedAdminBlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const UUsernameProjectsSlugRoute = UUsernameProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => UUsernameRoute,
} as any)
const UUsernameCaseStudiesSlugRoute =
  UUsernameCaseStudiesSlugRouteImport.update({
    id: '/case-studies/$slug',
    path: '/case-studies/$slug',
    getParentRoute: () => UUsernameRoute,
  } as any)
const UUsernameBlogSlugRoute = UUsernameBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => UUsernameRoute,
} as any)
const AuthenticatedAdminProjectsIdRoute =
  AuthenticatedAdminProjectsIdRouteImport.update({
    id: '/projects/$id',
    path: '/projects/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogIdRoute =
  AuthenticatedAdminBlogIdRouteImport.update({
    id: '/blog/$id',
    path: '/blog/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/case-studies': typeof AuthenticatedAdminCaseStudiesRoute
  '/admin/credentials': typeof AuthenticatedAdminCredentialsRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/recognition': typeof AuthenticatedAdminRecognitionRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/site-settings': typeof AuthenticatedAdminSiteSettingsRoute
  '/u/$username/about': typeof UUsernameAboutRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/u/$username/blog/$slug': typeof UUsernameBlogSlugRoute
  '/u/$username/case-studies/$slug': typeof UUsernameCaseStudiesSlugRoute
  '/u/$username/projects/$slug': typeof UUsernameProjectsSlugRoute
  '/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/projects/': typeof AuthenticatedAdminProjectsIndexRoute
  '/u/$username/blog/': typeof UUsernameBlogIndexRoute
  '/u/$username/case-studies/': typeof UUsernameCaseStudiesIndexRoute
  '/u/$username/projects/': typeof UUsernameProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/case-studies': typeof AuthenticatedAdminCaseStudiesRoute
  '/admin/credentials': typeof AuthenticatedAdminCredentialsRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/recognition': typeof AuthenticatedAdminRecognitionRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/site-settings': typeof AuthenticatedAdminSiteSettingsRoute
  '/u/$username/about': typeof UUsernameAboutRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/u/$username': typeof UUsernameIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/u/$username/blog/$slug': typeof UUsernameBlogSlugRoute
  '/u/$username/case-studies/$slug': typeof UUsernameCaseStudiesSlugRoute
  '/u/$username/projects/$slug': typeof UUsernameProjectsSlugRoute
  '/admin/blog': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsIndexRoute
  '/u/$username/blog': typeof UUsernameBlogIndexRoute
  '/u/$username/case-studies': typeof UUsernameCaseStudiesIndexRoute
  '/u/$username/projects': typeof UUsernameProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/case-studies': typeof AuthenticatedAdminCaseStudiesRoute
  '/_authenticated/admin/credentials': typeof AuthenticatedAdminCredentialsRoute
  '/_authenticated/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/_authenticated/admin/recognition': typeof AuthenticatedAdminRecognitionRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/site-settings': typeof AuthenticatedAdminSiteSettingsRoute
  '/u/$username/about': typeof UUsernameAboutRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/_authenticated/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/_authenticated/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/u/$username/blog/$slug': typeof UUsernameBlogSlugRoute
  '/u/$username/case-studies/$slug': typeof UUsernameCaseStudiesSlugRoute
  '/u/$username/projects/$slug': typeof UUsernameProjectsSlugRoute
  '/_authenticated/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/_authenticated/admin/projects/': typeof AuthenticatedAdminProjectsIndexRoute
  '/u/$username/blog/': typeof UUsernameBlogIndexRoute
  '/u/$username/case-studies/': typeof UUsernameCaseStudiesIndexRoute
  '/u/$username/projects/': typeof UUsernameProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/projects/$slug'
    | '/u/$username'
    | '/blog/'
    | '/case-studies/'
    | '/projects/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/case-studies'
    | '/admin/credentials'
    | '/admin/hero'
    | '/admin/messages'
    | '/admin/profile'
    | '/admin/recognition'
    | '/admin/services'
    | '/admin/site-settings'
    | '/u/$username/about'
    | '/admin/'
    | '/u/$username/'
    | '/admin/blog/$id'
    | '/admin/projects/$id'
    | '/u/$username/blog/$slug'
    | '/u/$username/case-studies/$slug'
    | '/u/$username/projects/$slug'
    | '/admin/blog/'
    | '/admin/projects/'
    | '/u/$username/blog/'
    | '/u/$username/case-studies/'
    | '/u/$username/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/projects/$slug'
    | '/blog'
    | '/case-studies'
    | '/projects'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/case-studies'
    | '/admin/credentials'
    | '/admin/hero'
    | '/admin/messages'
    | '/admin/profile'
    | '/admin/recognition'
    | '/admin/services'
    | '/admin/site-settings'
    | '/u/$username/about'
    | '/admin'
    | '/u/$username'
    | '/admin/blog/$id'
    | '/admin/projects/$id'
    | '/u/$username/blog/$slug'
    | '/u/$username/case-studies/$slug'
    | '/u/$username/projects/$slug'
    | '/admin/blog'
    | '/admin/projects'
    | '/u/$username/blog'
    | '/u/$username/case-studies'
    | '/u/$username/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/projects/$slug'
    | '/u/$username'
    | '/blog/'
    | '/case-studies/'
    | '/projects/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/case-studies'
    | '/_authenticated/admin/credentials'
    | '/_authenticated/admin/hero'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/profile'
    | '/_authenticated/admin/recognition'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/site-settings'
    | '/u/$username/about'
    | '/_authenticated/admin/'
    | '/u/$username/'
    | '/_authenticated/admin/blog/$id'
    | '/_authenticated/admin/projects/$id'
    | '/u/$username/blog/$slug'
    | '/u/$username/case-studies/$slug'
    | '/u/$username/projects/$slug'
    | '/_authenticated/admin/blog/'
    | '/_authenticated/admin/projects/'
    | '/u/$username/blog/'
    | '/u/$username/case-studies/'
    | '/u/$username/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  UUsernameRoute: typeof UUsernameRouteWithChildren
  BlogIndexRoute: typeof BlogIndexRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/': {
      id: '/u/$username/'
      path: '/'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof UUsernameIndexRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/u/$username/about': {
      id: '/u/$username/about'
      path: '/about'
      fullPath: '/u/$username/about'
      preLoaderRoute: typeof UUsernameAboutRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/_authenticated/admin/site-settings': {
      id: '/_authenticated/admin/site-settings'
      path: '/site-settings'
      fullPath: '/admin/site-settings'
      preLoaderRoute: typeof AuthenticatedAdminSiteSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/recognition': {
      id: '/_authenticated/admin/recognition'
      path: '/recognition'
      fullPath: '/admin/recognition'
      preLoaderRoute: typeof AuthenticatedAdminRecognitionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/profile': {
      id: '/_authenticated/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AuthenticatedAdminProfileRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hero': {
      id: '/_authenticated/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AuthenticatedAdminHeroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/credentials': {
      id: '/_authenticated/admin/credentials'
      path: '/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AuthenticatedAdminCredentialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/case-studies': {
      id: '/_authenticated/admin/case-studies'
      path: '/case-studies'
      fullPath: '/admin/case-studies'
      preLoaderRoute: typeof AuthenticatedAdminCaseStudiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/projects/': {
      id: '/u/$username/projects/'
      path: '/projects'
      fullPath: '/u/$username/projects/'
      preLoaderRoute: typeof UUsernameProjectsIndexRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/u/$username/case-studies/': {
      id: '/u/$username/case-studies/'
      path: '/case-studies'
      fullPath: '/u/$username/case-studies/'
      preLoaderRoute: typeof UUsernameCaseStudiesIndexRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/u/$username/blog/': {
      id: '/u/$username/blog/'
      path: '/blog'
      fullPath: '/u/$username/blog/'
      preLoaderRoute: typeof UUsernameBlogIndexRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/_authenticated/admin/projects/': {
      id: '/_authenticated/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/': {
      id: '/_authenticated/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AuthenticatedAdminBlogIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/u/$username/projects/$slug': {
      id: '/u/$username/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/u/$username/projects/$slug'
      preLoaderRoute: typeof UUsernameProjectsSlugRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/u/$username/case-studies/$slug': {
      id: '/u/$username/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/u/$username/case-studies/$slug'
      preLoaderRoute: typeof UUsernameCaseStudiesSlugRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/u/$username/blog/$slug': {
      id: '/u/$username/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/u/$username/blog/$slug'
      preLoaderRoute: typeof UUsernameBlogSlugRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/_authenticated/admin/projects/$id': {
      id: '/_authenticated/admin/projects/$id'
      path: '/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/$id': {
      id: '/_authenticated/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCaseStudiesRoute: typeof AuthenticatedAdminCaseStudiesRoute
  AuthenticatedAdminCredentialsRoute: typeof AuthenticatedAdminCredentialsRoute
  AuthenticatedAdminHeroRoute: typeof AuthenticatedAdminHeroRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminProfileRoute: typeof AuthenticatedAdminProfileRoute
  AuthenticatedAdminRecognitionRoute: typeof AuthenticatedAdminRecognitionRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSiteSettingsRoute: typeof AuthenticatedAdminSiteSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBlogIdRoute: typeof AuthenticatedAdminBlogIdRoute
  AuthenticatedAdminProjectsIdRoute: typeof AuthenticatedAdminProjectsIdRoute
  AuthenticatedAdminBlogIndexRoute: typeof AuthenticatedAdminBlogIndexRoute
  AuthenticatedAdminProjectsIndexRoute: typeof AuthenticatedAdminProjectsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCaseStudiesRoute: AuthenticatedAdminCaseStudiesRoute,
  AuthenticatedAdminCredentialsRoute: AuthenticatedAdminCredentialsRoute,
  AuthenticatedAdminHeroRoute: AuthenticatedAdminHeroRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminProfileRoute: AuthenticatedAdminProfileRoute,
  AuthenticatedAdminRecognitionRoute: AuthenticatedAdminRecognitionRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminSiteSettingsRoute: AuthenticatedAdminSiteSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBlogIdRoute: AuthenticatedAdminBlogIdRoute,
  AuthenticatedAdminProjectsIdRoute: AuthenticatedAdminProjectsIdRoute,
  AuthenticatedAdminBlogIndexRoute: AuthenticatedAdminBlogIndexRoute,
  AuthenticatedAdminProjectsIndexRoute: AuthenticatedAdminProjectsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface UUsernameRouteChildren {
  UUsernameAboutRoute: typeof UUsernameAboutRoute
  UUsernameIndexRoute: typeof UUsernameIndexRoute
  UUsernameBlogSlugRoute: typeof UUsernameBlogSlugRoute
  UUsernameCaseStudiesSlugRoute: typeof UUsernameCaseStudiesSlugRoute
  UUsernameProjectsSlugRoute: typeof UUsernameProjectsSlugRoute
  UUsernameBlogIndexRoute: typeof UUsernameBlogIndexRoute
  UUsernameCaseStudiesIndexRoute: typeof UUsernameCaseStudiesIndexRoute
  UUsernameProjectsIndexRoute: typeof UUsernameProjectsIndexRoute
}

const UUsernameRouteChildren: UUsernameRouteChildren = {
  UUsernameAboutRoute: UUsernameAboutRoute,
  UUsernameIndexRoute: UUsernameIndexRoute,
  UUsernameBlogSlugRoute: UUsernameBlogSlugRoute,
  UUsernameCaseStudiesSlugRoute: UUsernameCaseStudiesSlugRoute,
  UUsernameProjectsSlugRoute: UUsernameProjectsSlugRoute,
  UUsernameBlogIndexRoute: UUsernameBlogIndexRoute,
  UUsernameCaseStudiesIndexRoute: UUsernameCaseStudiesIndexRoute,
  UUsernameProjectsIndexRoute: UUsernameProjectsIndexRoute,
}

const UUsernameRouteWithChildren = UUsernameRoute._addFileChildren(
  UUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BlogSlugRoute: BlogSlugRoute,
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  UUsernameRoute: UUsernameRouteWithChildren,
  BlogIndexRoute: BlogIndexRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
